'use strict';
/**
 * Template PPTX Merger
 *
 * Merges template cover/closing slides (from uploaded PPTX) with
 * rich inner slides generated by pptxgenjs.
 *
 * Strategy:
 *   1. Open template PPTX → identify cover/closing slides
 *   2. Generate inner slides with pptxgenjs → get buffer
 *   3. Open pptxgenjs PPTX → extract slide XMLs + charts/media
 *   4. Copy pptxgenjs resources into template PPTX (with offset naming)
 *   5. Reassemble: cover + pptxgenjs inners + closing
 */

const JSZip = require('jszip');
const path = require('path');

// OOXML relationship type constants
const SLIDE_REL = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide';
const SLIDE_CT  = 'application/vnd.openxmlformats-officedocument.presentationml.slide+xml';
const CHART_CT  = 'application/vnd.openxmlformats-officedocument.drawingml.chart+xml';

/**
 * Merge template cover/closing with pptxgenjs-generated inner slides.
 *
 * @param {Buffer} templateBuffer  - The original template PPTX
 * @param {Array}  slideConfig     - [{index, type:'cover'|'layout_template'|'closing'}, ...]
 * @param {object} varMap          - Cover/closing variable replacements {key: value}
 * @param {Array}  richSlidesData  - Array of rich slide objects (for inner slides)
 * @param {string} themeName       - 'dark' | 'light' | 'corporate'
 * @returns {Promise<Buffer>}      - Merged PPTX buffer
 */
async function mergeTemplateWithRichSlides(templateBuffer, slideConfig, varMap, richSlidesData, themeName) {
  const PptxGenJS = require('pptxgenjs');
  const { renderRichInnerSlides } = require('./richSlideRenderer');

  // ── Step 1: Open template PPTX ──
  const templateZip = await new JSZip().loadAsync(templateBuffer);
  console.log(`[TemplateMerger] Template opened, files: ${Object.keys(templateZip.files).length}`);

  // Get slide entries sorted
  const slideEntries = Object.keys(templateZip.files)
    .filter(f => /^ppt\/slides\/slide\d+\.xml$/.test(f))
    .map(f => ({ file: f, num: parseInt(f.match(/slide(\d+)/)[1]) }))
    .sort((a, b) => a.num - b.num);

  console.log(`[TemplateMerger] Template slides: ${slideEntries.map(e => e.num).join(',')}, slideConfig: ${JSON.stringify(slideConfig.map(c => ({i:c.index,t:c.type})))}`);

  // Separate cover/closing from layout_template slides
  const coverSlides = [];
  const closingSlides = [];

  for (const entry of slideEntries) {
    const cfg = slideConfig.find(c => c.index === entry.num - 1);
    const slideType = cfg?.type || 'layout_template';

    if (slideType === 'cover' || slideType === 'closing') {
      let xml = await templateZip.file(entry.file).async('string');
      const relsFile = `ppt/slides/_rels/slide${entry.num}.xml.rels`;
      const relsXml = templateZip.file(relsFile)
        ? await templateZip.file(relsFile).async('string')
        : null;

      // Replace variables in cover/closing
      xml = _replacePlaceholders(xml, varMap);

      const target = slideType === 'cover' ? coverSlides : closingSlides;
      target.push({ xml, relsXml });
    }
    // Skip layout_template slides — they're replaced by rich inner slides
  }
  console.log(`[TemplateMerger] cover=${coverSlides.length} closing=${closingSlides.length} richSlides=${richSlidesData.length}`);

  // ── Step 2: Read template slide size, then generate inner slides with pptxgenjs ──
  const EMU_PER_INCH = 914400;
  let slideW = 13.33, slideH = 7.5; // default LAYOUT_WIDE
  const presXmlObj = templateZip.file('ppt/presentation.xml');
  if (presXmlObj) {
    const presXml = await presXmlObj.async('string');
    const sldSzMatch = presXml.match(/<p:sldSz\s+cx="(\d+)"\s+cy="(\d+)"/);
    if (sldSzMatch) {
      slideW = parseInt(sldSzMatch[1]) / EMU_PER_INCH;
      slideH = parseInt(sldSzMatch[2]) / EMU_PER_INCH;
    }
  }
  console.log(`[TemplateMerger] Template slide size: ${slideW.toFixed(2)}" x ${slideH.toFixed(2)}"`);

  const pptx = new PptxGenJS();
  pptx.defineLayout({ name: 'TPL_SIZE', width: slideW, height: slideH });
  pptx.layout = 'TPL_SIZE';
  const slideCount = renderRichInnerSlides(pptx, richSlidesData, themeName, {
    width: slideW, height: slideH, noFooter: true,
  });
  console.log(`[TemplateMerger] pptxgenjs rendered ${slideCount} inner slides (theme=${themeName})`);
  const richBuffer = await pptx.write({ outputType: 'nodebuffer' });
  console.log(`[TemplateMerger] pptxgenjs buffer size: ${richBuffer.length} bytes`);

  // ── Step 3: Extract slides + resources from pptxgenjs output ──
  const richZip = await new JSZip().loadAsync(richBuffer);
  const richSlideEntries = Object.keys(richZip.files)
    .filter(f => /^ppt\/slides\/slide\d+\.xml$/.test(f))
    .map(f => ({ file: f, num: parseInt(f.match(/slide(\d+)/)[1]) }))
    .sort((a, b) => a.num - b.num);

  // Rich mode: pptxgenjs uses absolute positioning, so we need a completely
  // blank layout — no shapes, no background elements from the template.
  const fallbackLayoutTarget = await _findOrCreateBlankLayout(templateZip);

  // ── Step 4: Copy resources from richZip → templateZip ──

  // 4a. Copy media files (images)
  const templateMedia = Object.keys(templateZip.files).filter(f => /^ppt\/media\//.test(f));
  const mediaMap = {}; // old name → new name
  const richMedia = Object.keys(richZip.files).filter(f => /^ppt\/media\//.test(f) && !richZip.files[f].dir);
  for (const mf of richMedia) {
    const fileObj = richZip.file(mf);
    if (!fileObj) continue;
    const baseName = path.basename(mf);
    const newName = `rich_${baseName}`;
    const newPath = `ppt/media/${newName}`;
    mediaMap[baseName] = newName;
    templateZip.file(newPath, await fileObj.async('nodebuffer'));
  }

  // 4b. Copy chart files
  const templateCharts = Object.keys(templateZip.files)
    .filter(f => /^ppt\/charts\/chart\d+\.xml$/.test(f));
  const chartOffset = templateCharts.reduce((max, f) => {
    const n = parseInt(f.match(/chart(\d+)/)[1]);
    return Math.max(max, n);
  }, 0);
  const chartMap = {}; // old chart num → new chart num

  const richCharts = Object.keys(richZip.files)
    .filter(f => /^ppt\/charts\/chart\d+\.xml$/.test(f) && !richZip.files[f].dir);
  for (const cf of richCharts) {
    const cfObj = richZip.file(cf);
    if (!cfObj) continue;
    const oldNum = parseInt(cf.match(/chart(\d+)/)[1]);
    const newNum = oldNum + chartOffset;
    chartMap[oldNum] = newNum;

    // Copy chart XML
    templateZip.file(`ppt/charts/chart${newNum}.xml`, await cfObj.async('string'));

    // Copy chart rels
    const chartRelsObj = richZip.file(`ppt/charts/_rels/chart${oldNum}.xml.rels`);
    if (chartRelsObj) {
      let relsContent = await chartRelsObj.async('string');
      // Update embedding references
      relsContent = relsContent.replace(/Target="([^"]*)"/g, (match, target) => {
        if (target.includes('embeddings/')) {
          const embBase = path.basename(target);
          const newEmb = `rich_${embBase}`;
          return `Target="${target.replace(embBase, newEmb)}"`;
        }
        return match;
      });
      templateZip.file(`ppt/charts/_rels/chart${newNum}.xml.rels`, relsContent);
    }
  }

  // 4c. Copy embedding files (Excel data for charts)
  const richEmbeddings = Object.keys(richZip.files).filter(f => /^ppt\/embeddings\//.test(f) && !richZip.files[f].dir);
  for (const ef of richEmbeddings) {
    const efObj = richZip.file(ef);
    if (!efObj) continue;
    const baseName = path.basename(ef);
    const newPath = `ppt/embeddings/rich_${baseName}`;
    templateZip.file(newPath, await efObj.async('nodebuffer'));
  }

  // ── Step 5: Extract inner slide XMLs with updated rels ──
  const innerSlides = [];
  for (const entry of richSlideEntries) {
    const slideObj = richZip.file(entry.file);
    if (!slideObj) continue;
    const xml = await slideObj.async('string');
    const relsFile = `ppt/slides/_rels/slide${entry.num}.xml.rels`;
    const relsObj = richZip.file(relsFile);
    let relsXml = relsObj ? await relsObj.async('string') : null;

    if (relsXml) {
      // Update slideLayout reference to template's layout
      relsXml = relsXml.replace(
        /Target="\.\.\/slideLayouts\/slideLayout\d+\.xml"/g,
        `Target="${fallbackLayoutTarget}"`
      );
      // Update chart references
      relsXml = relsXml.replace(/Target="\.\.\/charts\/chart(\d+)\.xml"/g, (_, n) => {
        const newN = chartMap[parseInt(n)] || parseInt(n);
        return `Target="../charts/chart${newN}.xml"`;
      });
      // Update media references
      relsXml = relsXml.replace(/Target="\.\.\/media\/([^"]+)"/g, (_, filename) => {
        const newName = mediaMap[filename] || filename;
        return `Target="../media/${newName}"`;
      });
    }

    // Prevent slideMaster shapes from showing — attribute goes on <p:sld> root, NOT <p:cSld>
    let fixedXml = xml;
    if (fixedXml.includes('<p:sld ') && !fixedXml.includes('showMasterSp=')) {
      fixedXml = fixedXml.replace('<p:sld ', '<p:sld showMasterSp="0" ');
    } else if (fixedXml.includes('<p:sld>') && !fixedXml.includes('showMasterSp=')) {
      fixedXml = fixedXml.replace('<p:sld>', '<p:sld showMasterSp="0">');
    }
    // Hide header/footer/slideNum/dateTime placeholders from master
    if (!fixedXml.includes('<p:hf')) {
      fixedXml = fixedXml.replace('</p:sld>', '<p:hf hdr="0" ftr="0" sldNum="0" dt="0"/></p:sld>');
    }
    // Debug: log shape count in inner slide
    const shapeCount = (fixedXml.match(/<p:sp\b/g) || []).length;
    const textCount = (fixedXml.match(/<a:t>/g) || []).length;
    console.log(`[TemplateMerger]   inner slide ${entry.num}: ${shapeCount} shapes, ${textCount} text nodes, xml=${fixedXml.length} bytes`);
    innerSlides.push({ xml: fixedXml, relsXml });
  }

  // ── Step 6: Assemble final slides ──
  const outputSlides = [...coverSlides, ...innerSlides, ...closingSlides];
  console.log(`[TemplateMerger] Assembling: ${coverSlides.length} cover + ${innerSlides.length} inner + ${closingSlides.length} closing = ${outputSlides.length} total`);

  await _rebuildPptxSlides(templateZip, outputSlides);

  // ── Step 7: Update Content_Types.xml for new charts ──
  if (richCharts.length > 0) {
    let ctXml = await templateZip.file('[Content_Types].xml').async('string');
    for (const [oldNum, newNum] of Object.entries(chartMap)) {
      const override = `<Override PartName="/ppt/charts/chart${newNum}.xml" ContentType="${CHART_CT}"/>`;
      if (!ctXml.includes(`/ppt/charts/chart${newNum}.xml`)) {
        ctXml = ctXml.replace('</Types>', override + '\n</Types>');
      }
    }
    templateZip.file('[Content_Types].xml', ctXml);
  }

  // Return merged PPTX buffer
  return await templateZip.generateAsync({ type: 'nodebuffer' });
}

// ── Find or create a blank slideLayout (no shapes) for pptxgenjs inner slides ──
const LAYOUT_REL_TYPE = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout';
const LAYOUT_CT_TYPE  = 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml';
const MASTER_REL_TYPE = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster';

async function _findOrCreateBlankLayout(zip) {
  const layoutFiles = Object.keys(zip.files)
    .filter(f => /^ppt\/slideLayouts\/slideLayout\d+\.xml$/.test(f) && !zip.files[f].dir)
    .sort();

  // Try to find an existing blank/minimal layout (type="blank" or very few shapes)
  for (const lf of layoutFiles) {
    const xml = await zip.file(lf).async('string');
    // type="blank" is the standard blank layout indicator
    if (xml.includes('type="blank"')) {
      const target = '../slideLayouts/' + path.basename(lf);
      console.log(`[TemplateMerger] Found existing blank layout: ${lf}`);
      return target;
    }
  }

  // Count shapes in each layout and pick the one with fewest
  let minShapes = Infinity, minFile = null;
  for (const lf of layoutFiles) {
    const xml = await zip.file(lf).async('string');
    const shapeCount = (xml.match(/<p:sp\b/g) || []).length;
    if (shapeCount < minShapes) {
      minShapes = shapeCount;
      minFile = lf;
    }
  }
  // If a layout with 0-1 shapes exists, use it
  if (minFile && minShapes <= 1) {
    const target = '../slideLayouts/' + path.basename(minFile);
    console.log(`[TemplateMerger] Using minimal layout (${minShapes} shapes): ${minFile}`);
    return target;
  }

  // ── No suitable layout found — create a blank one ──
  const maxNum = layoutFiles.reduce((max, f) => {
    const n = parseInt(f.match(/slideLayout(\d+)/)[1]);
    return Math.max(max, n);
  }, 0);
  const newNum = maxNum + 1;
  const newLayoutPath = `ppt/slideLayouts/slideLayout${newNum}.xml`;

  // Find slideMaster reference from first existing layout's rels
  let masterTarget = '../slideMasters/slideMaster1.xml';
  const firstRelsPath = `ppt/slideLayouts/_rels/slideLayout1.xml.rels`;
  const firstRelsObj = zip.file(firstRelsPath);
  if (firstRelsObj) {
    const rels = await firstRelsObj.async('string');
    const m = rels.match(/Target="([^"]*slideMaster[^"]*)"/);
    if (m) masterTarget = m[1];
  }

  // Blank layout XML — empty spTree, no shapes, showMasterSp="0" to block master shapes
  const blankXml = [
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
    '<p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"',
    '  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"',
    '  xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"',
    '  type="blank" preserve="1" showMasterSp="0">',
    '  <p:cSld name="RichBlank" showMasterSp="0"><p:spTree>',
    '    <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>',
    '    <p:grpSpPr/>',
    '  </p:spTree></p:cSld>',
    '</p:sldLayout>',
  ].join('\n');
  zip.file(newLayoutPath, blankXml);

  // Rels for the new layout → points to slideMaster
  const layoutRels = [
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">',
    `  <Relationship Id="rId1" Type="${MASTER_REL_TYPE}" Target="${masterTarget}"/>`,
    '</Relationships>',
  ].join('\n');
  zip.file(`ppt/slideLayouts/_rels/slideLayout${newNum}.xml.rels`, layoutRels);

  // Register in [Content_Types].xml
  const ctObj = zip.file('[Content_Types].xml');
  if (ctObj) {
    let ct = await ctObj.async('string');
    const override = `<Override PartName="/ppt/slideLayouts/slideLayout${newNum}.xml" ContentType="${LAYOUT_CT_TYPE}"/>`;
    if (!ct.includes(`/ppt/slideLayouts/slideLayout${newNum}.xml`)) {
      ct = ct.replace('</Types>', override + '\n</Types>');
      zip.file('[Content_Types].xml', ct);
    }
  }

  // Register in slideMaster's rels so it knows about this layout
  const masterFile = masterTarget.replace(/^\.\.\//, 'ppt/');
  const masterRelsFile = masterFile.replace(/slideMasters\//, 'slideMasters/_rels/') + '.rels';
  const masterRelsObj = zip.file(masterRelsFile);
  if (masterRelsObj) {
    let mr = await masterRelsObj.async('string');
    const existingRids = [...mr.matchAll(/Id="rId(\d+)"/g)].map(m => parseInt(m[1]));
    const newRid = (existingRids.length ? Math.max(...existingRids) : 0) + 1;
    const newRel = `<Relationship Id="rId${newRid}" Type="${LAYOUT_REL_TYPE}" Target="../slideLayouts/slideLayout${newNum}.xml"/>`;
    mr = mr.replace('</Relationships>', newRel + '\n</Relationships>');
    zip.file(masterRelsFile, mr);
  }

  console.log(`[TemplateMerger] Created blank layout: slideLayout${newNum}.xml`);
  return `../slideLayouts/slideLayout${newNum}.xml`;
}

// ── Placeholder replacement ──────────────────────────────────────────────────────
function _replacePlaceholders(xml, varMap) {
  for (const [key, val] of Object.entries(varMap)) {
    const ph = `{{${key}}}`;
    const replacement = String(val || '');

    // Quick check: if key doesn't appear anywhere in XML, skip entirely
    if (!xml.includes(key)) continue;

    // 1. Direct string replacement (works when placeholder is in a single run)
    if (xml.includes(ph)) {
      xml = xml.split(ph).join(replacement);
      continue; // Done for this key
    }

    // 2. Handle placeholder split across multiple <a:r> runs within a paragraph
    xml = xml.replace(/<a:p\b[^>]*>[\s\S]*?<\/a:p>/g, para => {
      // Collect text from all runs
      const textRuns = [];
      const runRegex = /<a:r>([\s\S]*?)<\/a:r>/g;
      let m;
      while ((m = runRegex.exec(para)) !== null) {
        const tMatch = m[1].match(/<a:t[^>]*>([\s\S]*?)<\/a:t>/);
        if (tMatch) textRuns.push(tMatch[1]);
      }
      const fullText = textRuns.join('');
      if (!fullText.includes(ph)) return para;

      // Replace placeholder in the concatenated text
      const replaced = fullText.replace(new RegExp(ph.replace(/[{}]/g, '\\$&'), 'g'), replacement);

      // Put all text into the first <a:r>, remove subsequent runs
      let firstRun = true;
      return para.replace(/<a:r>([\s\S]*?)<\/a:r>/g, (runMatch, runContent) => {
        if (firstRun) {
          firstRun = false;
          const newContent = runContent.replace(/<a:t[^>]*>[\s\S]*?<\/a:t>/, `<a:t>${replaced}</a:t>`);
          return `<a:r>${newContent}</a:r>`; // Keep <a:r> wrapper!
        }
        return ''; // Remove subsequent runs
      });
    });
  }
  return xml;
}

// ── Rebuild PPTX slides (adapted from docTemplateService._rebuildPptxSlides) ────
async function _rebuildPptxSlides(zip, outputSlides) {
  // Remove existing slide files
  Object.keys(zip.files)
    .filter(f => /^ppt\/slides\/slide\d+\.xml$/.test(f) ||
                 /^ppt\/slides\/_rels\/slide\d+\.xml\.rels$/.test(f))
    .forEach(f => zip.remove(f));

  // Write new slides
  const usedNoteTargets = new Set();
  for (let i = 0; i < outputSlides.length; i++) {
    const num = i + 1;
    zip.file(`ppt/slides/slide${num}.xml`, outputSlides[i].xml);
    if (outputSlides[i].relsXml) {
      let rels = outputSlides[i].relsXml;
      const noteM = rels.match(/Target="[^"]*notesSlide[^"]*"/);
      if (noteM) {
        const target = noteM[0];
        if (usedNoteTargets.has(target)) {
          rels = rels.replace(/<Relationship[^>]*notesSlide[^>]*\/>\s*/g, '');
        } else {
          usedNoteTargets.add(target);
        }
      }
      zip.file(`ppt/slides/_rels/slide${num}.xml.rels`, rels);
    }
  }

  // Update presentation.xml.rels
  const presRelsFile = zip.file('ppt/_rels/presentation.xml.rels');
  if (!presRelsFile) throw new Error('[TemplateMerger] ppt/_rels/presentation.xml.rels not found in ZIP');
  let presRels = await presRelsFile.async('string');
  presRels = presRels.replace(new RegExp(`<Relationship[^>]*Type="${SLIDE_REL.replace(/\//g, '\\/')}"[^>]*/>`,'g'), '');
  const existingIds = [...presRels.matchAll(/Id="rId(\d+)"/g)].map(m => parseInt(m[1]));
  const RID_OFFSET = (existingIds.length ? Math.max(...existingIds) : 0) + 1;

  const newRels = outputSlides.map((_, i) =>
    `<Relationship Id="rId${RID_OFFSET + i}" Type="${SLIDE_REL}" Target="slides/slide${i + 1}.xml"/>`
  ).join('\n');
  presRels = presRels.replace('</Relationships>', newRels + '\n</Relationships>');
  zip.file('ppt/_rels/presentation.xml.rels', presRels);

  // Update presentation.xml
  const presXmlFile = zip.file('ppt/presentation.xml');
  if (!presXmlFile) throw new Error('[TemplateMerger] ppt/presentation.xml not found in ZIP');
  let presXml = await presXmlFile.async('string');
  const existingSldIds = [...presXml.matchAll(/<p:sldId\s+id="(\d+)"/g)].map(m => parseInt(m[1]));
  const SLD_ID_START = (existingSldIds.length ? Math.max(...existingSldIds) : 255) + 1;
  const sldIds = outputSlides.map((_, i) =>
    `<p:sldId id="${SLD_ID_START + i}" r:id="rId${RID_OFFSET + i}"/>`
  ).join('');
  presXml = presXml.replace(/<p:sldIdLst>[\s\S]*?<\/p:sldIdLst>/, `<p:sldIdLst>${sldIds}</p:sldIdLst>`);
  zip.file('ppt/presentation.xml', presXml);

  // Update [Content_Types].xml
  const ctFile = zip.file('[Content_Types].xml');
  if (!ctFile) throw new Error('[TemplateMerger] [Content_Types].xml not found in ZIP');
  let ctXml = await ctFile.async('string');
  ctXml = ctXml.replace(/<Override[^>]*PartName="[^"]*\/slides\/slide\d+\.xml"[^>]*\/>\s*/g, '');
  const slideOverrides = outputSlides.map((_, i) =>
    `<Override PartName="/ppt/slides/slide${i + 1}.xml" ContentType="${SLIDE_CT}"/>`
  ).join('\n');
  ctXml = ctXml.replace('</Types>', slideOverrides + '\n</Types>');
  zip.file('[Content_Types].xml', ctXml);
}

/**
 * Generate a standalone rich PPTX (no template ZIP merge).
 * Reads template slide size, then uses pptxgenjs for everything:
 *   - Cover slide with template variable data
 *   - Rich inner slides
 *   - Closing slide
 *
 * @param {Buffer} templateBuffer - Template PPTX (only used to read slide size)
 * @param {object} varMap         - Cover/closing variable replacements
 * @param {Array}  richSlidesData - Array of rich slide objects
 * @param {string} themeName      - 'dark' | 'light' | 'corporate'
 * @returns {Promise<Buffer>}
 */
async function generateStandaloneRichPptx(templateBuffer, varMap, richSlidesData, themeName) {
  const PptxGenJS = require('pptxgenjs');
  const { renderRichInnerSlides, THEMES } = require('./richSlideRenderer');
  const { getIconDataUri } = require('./pptIcons');

  // ── Read template slide size ──
  const EMU_PER_INCH = 914400;
  let slideW = 10.0, slideH = 7.5;
  try {
    const zip = await new JSZip().loadAsync(templateBuffer);
    const presObj = zip.file('ppt/presentation.xml');
    if (presObj) {
      const presXml = await presObj.async('string');
      const m = presXml.match(/<p:sldSz\s[^>]*cx="(\d+)"[^>]*cy="(\d+)"/);
      if (m) {
        slideW = parseInt(m[1]) / EMU_PER_INCH;
        slideH = parseInt(m[2]) / EMU_PER_INCH;
      }
    }
  } catch (e) {
    console.warn('[StandaloneRich] Failed to read template size, using default:', e.message);
  }
  console.log(`[StandaloneRich] Slide size: ${slideW.toFixed(2)}" x ${slideH.toFixed(2)}", theme=${themeName}`);

  const pptx = new PptxGenJS();
  pptx.defineLayout({ name: 'TPL', width: slideW, height: slideH });
  pptx.layout = 'TPL';

  const theme = THEMES[themeName] || THEMES.dark;

  // ── Derive cover info from varMap ──
  // Find the most likely title, subtitle, author, date from template variables
  const coverTitle = _findCoverValue(varMap, ['cover_title', 'cover_department_name', 'cover_report_title', 'title']);
  const coverSubtitle = _findCoverValue(varMap, ['cover_subtitle', 'cover_project_name', 'subtitle']);
  const coverDate = _findCoverValue(varMap, ['cover_date', 'cover_report_date', 'date']);
  const coverAuthor = _findCoverValue(varMap, ['cover_author', 'cover_presenter', 'cover_name', 'author']);

  // ── Cover slide ──
  const coverSlide = pptx.addSlide();
  coverSlide.background = { color: theme.bg };

  // Top decorative bar
  const barH = slideH * 0.48;
  coverSlide.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: slideW, h: barH,
    fill: { color: theme.headerBg }, line: { width: 0 },
  });
  // Right accent block
  const navy = theme.isDark ? '0A0F1E' : '142244';
  coverSlide.addShape(pptx.ShapeType.rect, {
    x: slideW * 0.72, y: 0, w: slideW * 0.28, h: barH,
    fill: { color: navy }, line: { width: 0 },
  });
  // Brand
  coverSlide.addText('FOXLINK', {
    x: slideW * 0.72 + 0.15, y: 0.22, w: slideW * 0.28 - 0.3, h: 0.55,
    fontSize: 22, bold: true, color: 'FFFFFF', fontFace: 'Arial', align: 'right',
  });
  // Accent line
  coverSlide.addShape(pptx.ShapeType.rect, {
    x: 0, y: barH - 0.03, w: slideW, h: 0.08,
    fill: { color: theme.line }, line: { width: 0 },
  });
  // Main title
  coverSlide.addText(coverTitle || '報告', {
    x: 0.5, y: 0.8, w: slideW * 0.68, h: barH - 1.2,
    fontSize: Math.min(36, slideW * 3.6), bold: true, color: 'FFFFFF',
    fontFace: 'Arial', valign: 'middle', lineSpacingMultiple: 1.2,
  });
  // Subtitle
  if (coverSubtitle) {
    coverSlide.addText(coverSubtitle, {
      x: 0.5, y: barH + 0.15, w: slideW - 1, h: 0.7,
      fontSize: 18, color: theme.text, italic: true,
    });
  }
  // Author / Date
  const metaParts = [coverAuthor, coverDate].filter(Boolean);
  if (metaParts.length > 0) {
    coverSlide.addText(metaParts.join('    |    '), {
      x: 0.5, y: slideH - 1.0, w: slideW - 1, h: 0.35,
      fontSize: 12, color: theme.dim,
    });
  }

  // ── Inner slides (rich content) ──
  renderRichInnerSlides(pptx, richSlidesData, themeName, {
    width: slideW, height: slideH, noFooter: false,
  });

  // ── Closing slide ──
  const closingSlide = pptx.addSlide();
  closingSlide.background = { color: theme.bg };
  // Glow circle
  const cx = slideW / 2, cy = slideH * 0.38;
  closingSlide.addShape(pptx.ShapeType.ellipse, {
    x: cx - 2.0, y: cy - 1.0, w: 4.0, h: 4.0,
    fill: { color: theme.line, transparency: 85 }, line: { width: 0 },
  });
  closingSlide.addShape(pptx.ShapeType.ellipse, {
    x: cx - 1.2, y: cy, w: 2.4, h: 2.4,
    fill: { color: theme.line, transparency: 65 }, line: { width: 0 },
  });
  // Thank you text
  closingSlide.addText('Thank You', {
    x: 0.5, y: slideH * 0.42, w: slideW - 1, h: 1.2,
    fontSize: 38, bold: true, color: theme.text, align: 'center',
  });
  // Divider
  closingSlide.addShape(pptx.ShapeType.rect, {
    x: slideW * 0.35, y: slideH * 0.6, w: slideW * 0.3, h: 0.05,
    fill: { color: theme.accent }, line: { width: 0 },
  });
  // Brand
  closingSlide.addText('FOXLINK', {
    x: 0.5, y: slideH * 0.65, w: slideW - 1, h: 0.5,
    fontSize: 14, color: theme.dim, align: 'center',
  });

  console.log(`[StandaloneRich] Generated: 1 cover + ${richSlidesData.length} inner + 1 closing`);
  return await pptx.write({ outputType: 'nodebuffer' });
}

/** Helper: find first non-empty value from varMap matching candidate keys */
function _findCoverValue(varMap, candidates) {
  for (const key of candidates) {
    const v = varMap[key];
    if (v && String(v).trim()) return String(v).trim();
  }
  return '';
}

module.exports = { mergeTemplateWithRichSlides, generateStandaloneRichPptx };
